version: '3.8'

services:
  healthcare_mysql:
    image: mysql:8.0
    container_name: healthcare_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect="SET NAMES utf8mb4" --skip-character-set-client-handshake
    ports:
      - "3306:3306"
    volumes:
      - healthcare_mysql_data:/var/lib/mysql
    networks:
      - healthcare_network

  healthcare_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: healthcare_phpmyadmin
    environment:
      PMA_HOST: healthcare_mysql
      PMA_PORT: 3306
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "6080:80"
    depends_on:
      - healthcare_mysql
    networks:
      - healthcare_network

volumes:
  healthcare_mysql_data:

networks:
  healthcare_network:
    driver: bridge