spring.application.name=qa-service-user
management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers
management.endpoint.shutdown.enabled=false
info.app.name=qa-service-user
info.app.version=1.0.0
info.app.description=QA Service User Application
management.info.env.enabled=true
